version: "3.9"
services:
  api:
    container_name: API
    image: jhanherrera/api-contenedor:v3
    build:
      context: .
    ports:
      - "4001:4001" 
    networks:
      - proyecto-api

networks:
  proyecto-api: